name: DansListMarketplace
description: AI Agent Marketplace Activity Tracker
networks:
  - id: 84532  # Base Sepolia (updated from Arbitrum Sepolia per Tasklist)
    start_block: 0
    contracts:
      - name: VerifiableMarketplace
        abi_file_path: ../artifacts/contracts/VerifiableMarketplace.sol/VerifiableMarketplace.json
        address: ${MARKETPLACE_ADDRESS}  # Injected dynamically via sync script
        handler: ./src/EventHandlers.ts
        events:
          - event: ListingCreated        # ✓ Exists in contract
          - event: ListingPurchased      # ✓ Exists in contract (was PurchaseInitiated)
          - event: MarketplaceFeeUpdated # ✓ Exists in contract
          - event: FundsWithdrawn        # ✓ Exists in contract

# GraphQL schema location
schema_path: ./schema.graphql

# Event handlers location
handler_path: ./src/EventHandlers.ts
